# Generated by Django 2.0.13 on 2020-12-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201229_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='kindness',
        ),
    ]
