# Generated by Django 3.1 on 2020-12-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0002_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
